spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/labelflow_dev
    username: labelflow_user
    password: Test@123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG