spring:
  application:
    name: changeorder-service

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  kafka:
    consumer:
      group-id: changeorder-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer