server:
  port: 8082

spring:
  application:
    name: changeorder-service

  datasource:
    url: jdbc:postgresql://localhost:5432/labelflow_changeorder_db
    username: labelflow_changeorder_user
    password: ChangeOrder@123

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: changeorder-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

